language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install "pytest>=3.6" pytest_cov
  - python setup.py develop
script: 
  - py.test tests/ --cov simuling/
  - py.test simuling/ --doctest-modules --cov simuling/ --cov-append
  - py.test --pep8
